name = "babygrad-tutorial"
account_id = "facf6619808dc039df729531bbb26d1d"
compatibility_date = "2026-02-01"

[[routes]]
pattern = "babygrad.emilycogsdill.com"
custom_domain = true

[assets]
directory = "./public"
